[package]
name = "save-point"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "6.0.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
crossterm = "0.26"
ratatui = "0.20"
